library(lubridate)
dat0 <- read.table("household_power_consumption.txt",header=T,sep=";",nrow=100000,na.strings="?")
dat <- dat0[min(which(dat0$Date=="1/2/2007")):max(which(dat0$Date=="2/2/2007")),]
datetime <- dmy_hms(paste(dat$Date,dat$Time))
Sys.setlocale("LC_TIME", "English")
png("plot3.png",width=480,height=480)
plot(datetime,dat$Sub_metering_1,"l",xlab="",ylab="Energy sub metering")
lines(datetime,dat$Sub_metering_2,"l",col="red")
lines(datetime,dat$Sub_metering_3,"l",col="blue")
legend("topright",lty=1,col = c("black","red","blue"), legend = c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"))
dev.off()